### ISSUE TITLE
Disconnection : An item with the same key has already been added

### ISSUE THREAD

**Issue by fMichaleczek** [SeeminglyScience/GetClrCallStack#4]
I found this bug when I was testing your module.

It reproduces on any target (Windows PowerShell, PowerShell, PowerShell Preview).

**Steps to reproduce :** 

- open a powershell or pwsh instance then enter a long running command 
`dir | %{ start-sleep -Seconds 2 }`
- execute the Get-ClrCallStack command on another pwsh instance 
`Get-ClrCallStack -Id 12376`
- stop the long running command with Ctrl + C
- execute again the Get-ClrCallStack command
`Get-ClrCallStack -Id 12376`

**Expected behavior :**
```
it works !
```

**Actual behavior :**
```
Get-ClrCallStack: An item with the same key has already been added
```

**Error details :**
```
Exception             :
    Type       : System.ArgumentException
    Message    : An item with the same key has already been added. Key: 22
    TargetSite :
        Name          : ThrowAddingDuplicateWithKeyArgumentException
        DeclaringType : System.ThrowHelper, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Source     : System.Private.CoreLib
    HResult    : -2147024809
    StackTrace :
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at GetClrCallStack.GetClrCallStackCommand.ProcessRecord() in D:\a\GetClrCallStack\GetClrCallStack\src\GetClrCallStack\GetClrCallStackCommand.cs:line 109
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Get-ClrCallStack], ArgumentException
FullyQualifiedErrorId : System.ArgumentException,GetClrCallStack.GetClrCallStackCommand
InvocationInfo        :
    MyCommand        : Get-ClrCallStack
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 62
    Line             : Get-ClrCallStack -Id 12376
    PositionMessage  : At line:1 char:1
                       + Get-ClrCallStack -Id 12376
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-ClrCallStack
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

```

**Environment data :**
```
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS > Get-Module GetClrCallStack

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     1.0.0                 GetClrCallStack                     Get-ClrCallStack
```

**Comment by SeeminglyScience** [comment]
Thanks @fMichaleczek! Same as #3 I think, at least the fix will be the same. But I'll definitely test this scenario too
